# Generated by Django 2.0.13 on 2019-05-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpleadoModelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idnum', models.IntegerField()),
                ('paterno', models.CharField(max_length=50)),
                ('materno', models.CharField(max_length=50)),
                ('nombres', models.CharField(max_length=50)),
                ('fono', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('ingreso', models.IntegerField()),
            ],
        ),
    ]
